/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.BoxLayout;
import javax.swing.SpringLayout;
import s4.EstadoMotor;
import s4.Cliente;

public class PanelBotones extends javax.swing.JPanel {

    public static EstadoMotor estadoMotor;

    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        estadoMotor = EstadoMotor.APAGADO;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonApEn1 = new javax.swing.JToggleButton();
        estado = new javax.swing.JLabel();
        botonApEn = new javax.swing.JToggleButton();
        mandos = new javax.swing.JLabel();
        botonAcelerar = new javax.swing.JToggleButton();
        botonFrenar = new javax.swing.JToggleButton();

        botonApEn1.setBackground(new java.awt.Color(153, 153, 153));
        botonApEn1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonApEn1.setForeground(new java.awt.Color(0, 255, 102));
        botonApEn1.setText("ENCENDER");
        botonApEn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonApEn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonApEn1ActionPerformed(evt);
            }
        });

        estado.setBackground(new java.awt.Color(153, 153, 153));
        estado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        estado.setForeground(new java.awt.Color(255, 0, 51));
        estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estado.setText("APAGADO");
        estado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        estado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        estado.setOpaque(true);

        botonApEn.setBackground(new java.awt.Color(153, 153, 153));
        botonApEn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonApEn.setForeground(new java.awt.Color(0, 255, 102));
        botonApEn.setText("ENCENDER");
        botonApEn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonApEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonApEnActionPerformed(evt);
            }
        });

        mandos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mandos.setText("mandos");

        botonAcelerar.setBackground(new java.awt.Color(153, 153, 153));
        botonAcelerar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonAcelerar.setForeground(new java.awt.Color(0, 0, 0));
        botonAcelerar.setText("ACELERAR");
        botonAcelerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcelerarActionPerformed(evt);
            }
        });

        botonFrenar.setBackground(new java.awt.Color(153, 153, 153));
        botonFrenar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonFrenar.setForeground(new java.awt.Color(0, 0, 0));
        botonFrenar.setText("FRENAR");
        botonFrenar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFrenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(mandos)
                        .addGap(78, 78, 78)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(botonApEn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(botonAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(botonFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mandos)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonApEn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonApEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonApEnActionPerformed
        if (estadoMotor.equals(EstadoMotor.APAGADO)) {
            estado.setText("ENCENDIDO");
            botonApEn.setForeground(Color.red);
            botonApEn.setText("APAGAR");
            estadoMotor = EstadoMotor.ENCENDIDO;
        } else {
            estado.setText("APAGADO");
            botonApEn.setForeground(Color.green);
            botonApEn.setText("ENCENDER");
            estadoMotor = EstadoMotor.APAGADO;
        }

    }//GEN-LAST:event_botonApEnActionPerformed

    private void botonApEn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonApEn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonApEn1ActionPerformed

    private void botonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcelerarActionPerformed
        if (estadoMotor.equals(EstadoMotor.ENCENDIDO) && botonAcelerar.isSelected()) {
            estadoMotor = EstadoMotor.ACELERANDO;
            estado.setText("ACELERANDO");
            botonAcelerar.setText("Soltar acelerador");
            botonAcelerar.setForeground(Color.RED);

        } else if (estadoMotor.equals(EstadoMotor.ACELERANDO) && !botonAcelerar.isSelected()) {
            estadoMotor = EstadoMotor.ENCENDIDO;
            botonAcelerar.setText("ACELERAR");
            botonAcelerar.setForeground(Color.BLACK);
            estado.setText("ENCENDIDO");
        }
    }//GEN-LAST:event_botonAcelerarActionPerformed

    private void botonFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFrenarActionPerformed
        if (estadoMotor.equals(EstadoMotor.ENCENDIDO) && botonFrenar.isSelected()) {
            estadoMotor = EstadoMotor.FRENANDO;
            estado.setText("FRENANDO");
            botonFrenar.setText("Soltar freno");
            botonFrenar.setForeground(Color.RED);

        } else if (estadoMotor.equals(EstadoMotor.FRENANDO) && !botonFrenar.isSelected()) {
            estadoMotor = EstadoMotor.ENCENDIDO;
            botonFrenar.setText("FRENAR");
            botonFrenar.setForeground(Color.BLACK);
            estado.setText("ENCENDIDO");
        }
    }//GEN-LAST:event_botonFrenarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAcelerar;
    private javax.swing.JToggleButton botonApEn;
    private javax.swing.JToggleButton botonApEn1;
    private javax.swing.JToggleButton botonFrenar;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel mandos;
    // End of variables declaration//GEN-END:variables
}
