/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author fedeg
 */
public class Salpicadero extends javax.swing.JPanel {

    /**
     * Creates new form Salpicadero
     */
    public Salpicadero() {
        initComponents();
    }

    public void setVelocimetro(String velocidad) {
        //System.err.println(velocidad);
        velocimetro.setText(velocidad);
    }

    public void setContadorReciente(String contador) {
        contadorReciente.setText(contador);
    }

    public void setContadorTotal(String contador) {
        contadorTotal.setText(contador);
    }

    public void setCuentaRevoluciones(String revoluciones) {
        cuentaRevoluciones.setText(revoluciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salpicadero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        velocimetro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contadorReciente = new javax.swing.JLabel();
        contadorTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cuentaRevoluciones = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        salpicadero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        salpicadero.setForeground(new java.awt.Color(0, 0, 0));
        salpicadero.setText("Salpicadero");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Velocímetro");

        velocimetro.setBackground(new java.awt.Color(153, 153, 153));
        velocimetro.setForeground(new java.awt.Color(204, 0, 0));
        velocimetro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        velocimetro.setText("0 km/h");
        velocimetro.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cuentakilómetros");

        contadorReciente.setBackground(new java.awt.Color(153, 153, 153));
        contadorReciente.setForeground(new java.awt.Color(204, 0, 0));
        contadorReciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorReciente.setText("0 km");
        contadorReciente.setOpaque(true);

        contadorTotal.setBackground(new java.awt.Color(153, 153, 153));
        contadorTotal.setForeground(new java.awt.Color(204, 0, 0));
        contadorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorTotal.setText("0 km");
        contadorTotal.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cuentarevoluciones");

        cuentaRevoluciones.setBackground(new java.awt.Color(153, 153, 153));
        cuentaRevoluciones.setForeground(new java.awt.Color(204, 0, 0));
        cuentaRevoluciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuentaRevoluciones.setText("0 RPM");
        cuentaRevoluciones.setOpaque(true);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("contador reciente");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("contador total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(salpicadero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(velocimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(cuentaRevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(contadorReciente, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(contadorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salpicadero)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(velocimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(contadorReciente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contadorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cuentaRevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contadorReciente;
    private javax.swing.JLabel contadorTotal;
    private javax.swing.JLabel cuentaRevoluciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel salpicadero;
    private javax.swing.JLabel velocimetro;
    // End of variables declaration//GEN-END:variables
}
